require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe WigglesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Wiggle. As you add validations to Wiggle, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WigglesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all wiggles as @wiggles" do
      wiggle = Wiggle.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:wiggles)).to eq([wiggle])
    end
  end

  describe "GET show" do
    it "assigns the requested wiggle as @wiggle" do
      wiggle = Wiggle.create! valid_attributes
      get :show, {:id => wiggle.to_param}, valid_session
      expect(assigns(:wiggle)).to eq(wiggle)
    end
  end

  describe "GET new" do
    it "assigns a new wiggle as @wiggle" do
      get :new, {}, valid_session
      expect(assigns(:wiggle)).to be_a_new(Wiggle)
    end
  end

  describe "GET edit" do
    it "assigns the requested wiggle as @wiggle" do
      wiggle = Wiggle.create! valid_attributes
      get :edit, {:id => wiggle.to_param}, valid_session
      expect(assigns(:wiggle)).to eq(wiggle)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Wiggle" do
        expect {
          post :create, {:wiggle => valid_attributes}, valid_session
        }.to change(Wiggle, :count).by(1)
      end

      it "assigns a newly created wiggle as @wiggle" do
        post :create, {:wiggle => valid_attributes}, valid_session
        expect(assigns(:wiggle)).to be_a(Wiggle)
        expect(assigns(:wiggle)).to be_persisted
      end

      it "redirects to the created wiggle" do
        post :create, {:wiggle => valid_attributes}, valid_session
        expect(response).to redirect_to(Wiggle.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved wiggle as @wiggle" do
        post :create, {:wiggle => invalid_attributes}, valid_session
        expect(assigns(:wiggle)).to be_a_new(Wiggle)
      end

      it "re-renders the 'new' template" do
        post :create, {:wiggle => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested wiggle" do
        wiggle = Wiggle.create! valid_attributes
        put :update, {:id => wiggle.to_param, :wiggle => new_attributes}, valid_session
        wiggle.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested wiggle as @wiggle" do
        wiggle = Wiggle.create! valid_attributes
        put :update, {:id => wiggle.to_param, :wiggle => valid_attributes}, valid_session
        expect(assigns(:wiggle)).to eq(wiggle)
      end

      it "redirects to the wiggle" do
        wiggle = Wiggle.create! valid_attributes
        put :update, {:id => wiggle.to_param, :wiggle => valid_attributes}, valid_session
        expect(response).to redirect_to(wiggle)
      end
    end

    describe "with invalid params" do
      it "assigns the wiggle as @wiggle" do
        wiggle = Wiggle.create! valid_attributes
        put :update, {:id => wiggle.to_param, :wiggle => invalid_attributes}, valid_session
        expect(assigns(:wiggle)).to eq(wiggle)
      end

      it "re-renders the 'edit' template" do
        wiggle = Wiggle.create! valid_attributes
        put :update, {:id => wiggle.to_param, :wiggle => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested wiggle" do
      wiggle = Wiggle.create! valid_attributes
      expect {
        delete :destroy, {:id => wiggle.to_param}, valid_session
      }.to change(Wiggle, :count).by(-1)
    end

    it "redirects to the wiggles list" do
      wiggle = Wiggle.create! valid_attributes
      delete :destroy, {:id => wiggle.to_param}, valid_session
      expect(response).to redirect_to(wiggles_url)
    end
  end

end
